[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "security-app"
version = "0.1.0"
description = "Run STIG/Checklist and report results."
requires-python = ">=3.10"
dependencies = ["pandas"]

[project.scripts]
security-app = "security_app.app.cli:main"

[tool.setuptools]
packages = ["security_app",
            "security_app.app",
            "security_app.core",
            "security_app.parsers",
            "security_app.reporting",
            "security_app.utils"]
